version: "3"
services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        env_file: .env
        environment:
            - PORT=${PORT}
            - DB_URL=${DB_URL}
            - JWT_SECRET=${JWT_SECRET}
        volumes:
            - images:/app/images
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        volumes:
            - pg_data:/var/lib/postgresql/data
        env_file: .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    migrate:
        image: migrate/migrate
        volumes:
            - ./backend/sql/schema:/migrations
        env_file: .env
        environment:
            - DB_URL=${DB_URL}

        entrypoint:
            [
                "migrate",
                "-path",
                "/migrations",
                "-database",
                "${DB_URL}",
            ]
        
        command: ["up"]
        depends_on:
            - postgres

    frontend:
        build:
            context: ./frontend
        ports:
            - "8080:8080"

volumes:
    pg_data:
    images: