version: "3"
services:
    backend:
        container_name: backend
        env_file: .env
        build:
            context: ./backend
        ports:
            - "8000:8000"
        environment:
            - PORT=${PORT}
            - DB_URL=${DB_URL}
            - JWT_SECRET=${JWT_SECRET}
        volumes:
            - images:/app/images
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:latest
        volumes:
            - pg_data:/var/lib/postgresql/data
        env_file: .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    frontend:
        container_name: frontend
        env_file: .env
        build:
            context: ./frontend
            args:
                - VITE_API_URL_ARG=${VITE_API_URL_ARG}
                - VITE_IMG_URL_ARG=${VITE_IMG_URL_ARG}
        volumes:
            - fe_build:/app/dist
        depends_on:
            - backend

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 8080:8080
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - fe_build:/usr/share/nginx/html
        depends_on:
            - frontend
            - backend

volumes:
    pg_data:
    images:
    fe_build: